# Generated by Django 2.1.7 on 2019-03-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissercat', '0002_auto_20190311_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dissercat.Category'),
            preserve_default=False,
        ),
    ]
