# Generated by Django 2.1.7 on 2019-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissercat', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fetched',
            field=models.BooleanField(default=False),
        ),
    ]
